[package]
name = "musig"
version = "0.1.0"
authors = ["Cathie Yun <cathieyun@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
merlin = "1.0.1"
rand = "0.6"
subtle = "2"
curve25519-dalek = { version = "1.0.1", features = ["serde"] }
serde = { version = "1.0", features=["derive"] }
